### ISSUE TITLE
Allow choosing Opal versions

### ISSUE THREAD

**Issue by wied03** [cj/opal-webpack#13]
1) the easy path - use bundled opal runtime and compiler with tool. easy to get started. safe due to no mixing and matching compiler and runtime versions
2) your own static file (instead of vendor/opal-compiler.js)
3) one fetched from Bundler on the fly
4) stub out opal requires and supply it outside of webpack (like I did with https://github.com/wied03/webpack_spec_sandbox).

**Comment by cj** [comment]
4) is what I do here https://github.com/cj/opal-connect/blob/master/lib/opal/connect/rake_task.rb and then I include it like:

```
config.entry = [
    './.connect/opal.js',
    './.connect/entry.js'
  ]
```

We might want to do 1) and 4).  so the latest version of opal compiled comes with opal-webpack so you can just include the loader and get going.  Thoughts?

**Comment by wied03** [comment]
A lot of in progress work here already in the other branch but #4 would support that. can explain more later.

**Comment by wied03** [comment]
Sorry.  Hasty response. That's exactly what I was thinking. Only part of #4
in the branch is it'll stub out opal requires for you if you ask.

But yeah. I was thinking you can lick whichever you want of the 4 and a
default is there like you said.

sent from my mobile device

**Comment by wied03** [comment]
By opal requires, mean if I have a bunch of code (stuff from GEMs, wherever) and that code does a `require 'opal'`, which isn't uncommon, and you've chosen to load it outside of webpack (like your example), then you don't want webpack to include anything. basically just syntatic sugar for adding 'opal' to the stubs list.

**Comment by wied03** [comment]
1, 2, and 4 are already done in the choose_opal_version branch. My next step is to work on 3 and then send you another PR.

**Comment by cj** [comment]
Great.  I'll be around tonight 8pm central.

**Comment by wied03** [comment]
I may not be around tonight. Should be tomorrow though.

**Comment by wied03** [comment]
This is now coded up. I just need to document how the config works in the README and submit another PR.
