### ISSUE TITLE
Support sprockets requires

### ISSUE THREAD

**Issue by wied03** [cj/opal-webpack#2]
Support sprockets style requires (e.g. `#= require some_file`). May or may not make sense to support JS sprockets requires (`//= require some_file`) here. That might belong in a separate loader.

As part of this effort, see if, assuming cache PR merge, `prepend.push(```require('!!${options.currentLoader}?${flat}!${resolved}');```)` can be refactored to something like `prepend.push(```require('!!${resolved}?${flat}');```)`. It would eliminate the need for the currentLoader dependency and would let webpack pick the loader based on the file extension.

**Comment by cj** [comment]
I think it would be a good addition, would avoid having to do https://gist.github.com/cf06a3ea79632261061030deeaf8bdbb.  This might make a good flag/compiler option.

**Comment by wied03** [comment]
In the interest of trying to keep this loader from getting too big, I think support for a pure sprockets loader (`//= require some_file`) belongs in another project/loader. Maybe Opal style in this one (`#= require some_file`) but I think even that would be more modular in a separate project.

**Comment by cj** [comment]
I think having the opal style would be a nice addition, that way everything would be 100% opal.

In my experience, having:

```
if RUBY_ENGINE == 'opal'
  `require('app/components/layout/theme.css')`
  `require('app/components/layout/theme.js')`
end
```

is ugly and actually confuses some people.

**Comment by wied03** [comment]
Not saying it's not useful, just saying that the line "do only a single task" in http://webpack.github.io/docs/how-to-write-a-loader.html resonated with me.

**Comment by cj** [comment]
I agree.  So would this be something like `sprockets-type-require-loader`?

**Comment by wied03** [comment]
Something like that. I almost worry this loader is too big but I think most of the stuff that's currently being worked on is fairly core.

**Comment by wied03** [comment]
Closing since would go in a separate loader.
