### ISSUE TITLE
Include stubs when adding bundler load paths

### ISSUE THREAD

**Issue by wied03** [cj/opal-webpack#24]
Currently, when the Bundler context is present, a `Bundler.require` is issued which will cause most Opal GEMs to add themselves to the Opal load path in Ruby that this loader then incorporates into its load path.

Some GEMS that are sufficiently complex (https://github.com/wied03/opal-factory_girl is one example) also stub Opal files when the GEM is required on the MRI side.

It might make sense to incorporate the stubbed files in the same way when the `Bundler.require` is issued.

**Comment by wied03** [comment]
@cj  - thoughts?

**Comment by cj** [comment]
I agree, that would make sense.
