### ISSUE TITLE
Add conditional for compiler

### ISSUE THREAD

**Issue by cj** [cj/opal-webpack#8]
Need to add a conditional to the compiler here https://github.com/cj/opal-webpack/blob/master/lib/getCompiler.js#L21 as of >= 0.10.0.beta2 ` Opal.Opal.Compiler.$new` needs to be ` Opal.Opal.$$scope.Compiler.$new`

**Comment by wied03** [comment]
Yeah, I was going to address that as part of #6.

**Comment by cj** [comment]
sounds good.  I'll close this out.
